In [36]:
import pandas as pd 
import numpy as np 
import plotly.express as px 
from pathlib import Path

In [37]:
base_dir  = Path.cwd().parent
data_path = base_dir / "data" / "owid-co2-data.csv"
a = pd.read_csv(data_path)

In [38]:
a.info()

<class 'pandas.DataFrame'>
RangeIndex: 50411 entries, 0 to 50410
Data columns (total 79 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   country                                    50411 non-null  str
 1   year                                       50411 non-null  int64
 2   iso_code                                   42480 non-null  str
 3   population                                 41167 non-null  float64
 4   gdp                                        15251 non-null  float64
 5   cement_co2                                 29173 non-null  float64
 6   cement_co2_per_capita                      25648 non-null  float64
 7   co2                                        29384 non-null  float64
 8   co2_growth_abs                             27216 non-null  float64
 9   co2_growth_prct                            26239 non-null  float64
 10  co2_including_luc                          23796 non-null  float64
 11  co2_including_luc_growth_abs               23496 non-null  float64
 12  co2_including_luc_growth_prct              23496 non-null  float64
 13  co2_including_luc_per_capita               23757 non-null  float64
 14  co2_including_luc_per_gdp                  16790 non-null  float64
 15  co2_including_luc_per_unit_energy          10133 non-null  float64
 16  co2_per_capita                             26509 non-null  float64
 17  co2_per_gdp                                17528 non-null  float64
 18  co2_per_unit_energy                        10826 non-null  float64
 19  coal_co2                                   21925 non-null  float64
 20  coal_co2_per_capita                        21314 non-null  float64
 21  consumption_co2                            5053 non-null   float64
 22  consumption_co2_per_capita                 4643 non-null   float64
 23  consumption_co2_per_gdp                    4448 non-null   float64
 24  cumulative_cement_co2                      29151 non-null  float64
 25  cumulative_co2                             27563 non-null  float64
 26  cumulative_co2_including_luc               23796 non-null  float64
 27  cumulative_coal_co2                        21925 non-null  float64
 28  cumulative_flaring_co2                     16111 non-null  float64
 29  cumulative_gas_co2                         18147 non-null  float64
 30  cumulative_luc_co2                         37450 non-null  float64
 31  cumulative_oil_co2                         25458 non-null  float64
 32  cumulative_other_co2                       3254 non-null   float64
 33  energy_per_capita                          10586 non-null  float64
 34  energy_per_gdp                             7787 non-null   float64
 35  flaring_co2                                16174 non-null  float64
 36  flaring_co2_per_capita                     14910 non-null  float64
 37  gas_co2                                    18147 non-null  float64
 38  gas_co2_per_capita                         17446 non-null  float64
 39  ghg_excluding_lucf_per_capita              35842 non-null  float64
 40  ghg_per_capita                             36179 non-null  float64
 41  land_use_change_co2                        37450 non-null  float64
 42  land_use_change_co2_per_capita             36635 non-null  float64
 43  methane                                    38150 non-null  float64
 44  methane_per_capita                         36179 non-null  float64
 45  nitrous_oxide                              38500 non-null  float64
 46  nitrous_oxide_per_capita                   36439 non-null  float64
 47  oil_co2                                    25459 non-null  float64
 48  oil_co2_per_capita                         24722 non-null  float64
 49  other_co2_per_capita                       2659 non-null   float64
 50  other_industry_co2                         3254 non-null   float64
 51  primary_energy_consumption                 10631 non-null  float64
 52  share_global_cement_co2                    22270 non-null  float64
 53  share_global_co2                           27563 non-null  float64
 54  share_global_co2_including_luc             23796 non-null  float64
 55  share_global_coal_co2                      21925 non-null  float64
 56  share_global_cumulative_cement_co2         22270 non-null  float64
 57  share_global_cumulative_co2                27563 non-null  float64
 58  share_global_cumulative_co2_including_luc  23796 non-null  float64
 59  share_global_cumulative_coal_co2           21925 non-null  float64
 60  share_global_cumulative_flaring_co2        11089 non-null  float64
 61  share_global_cumulative_gas_co2            15167 non-null  float64
 62  share_global_cumulative_luc_co2            37450 non-null  float64
 63  share_global_cumulative_oil_co2            23833 non-null  float64
 64  share_global_cumulative_other_co2          2170 non-null   float64
 65  share_global_flaring_co2                   11089 non-null  float64
 66  share_global_gas_co2                       15167 non-null  float64
 67  share_global_luc_co2                       37450 non-null  float64
 68  share_global_oil_co2                       23833 non-null  float64
 69  share_global_other_co2                     2170 non-null   float64
 70  share_of_temperature_change_from_ghg       41238 non-null  float64
 71  temperature_change_from_ch4                38280 non-null  float64
 72  temperature_change_from_co2                41238 non-null  float64
 73  temperature_change_from_ghg                41238 non-null  float64
 74  temperature_change_from_n2o                38280 non-null  float64
 75  total_ghg                                  38150 non-null  float64
 76  total_ghg_excluding_lucf                   37813 non-null  float64
 77  trade_co2                                  4712 non-null   float64
 78  trade_co2_share                            4712 non-null   float64
dtypes: float64(76), int64(1), str(2)
memory usage: 30.4 MB

In [39]:
a.shape

(50411, 79)

In [40]:
a.describe()

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,50411.000000,4.116700e+04,1.525100e+04,29173.000000,25648.000000,29384.000000,27216.000000,26239.000000,23796.000000,23496.000000,...,2170.000000,41238.000000,38280.000000,41238.000000,41238.000000,38280.000000,38150.000000,37813.000000,4712.000000,4712.000000
mean,1920.349249,6.017294e+07,3.300495e+11,7.890109,0.060026,420.227035,6.268847,42.598225,544.144592,7.483698,...,7.190616,2.272236,0.002871,0.008014,0.011224,0.000509,490.799608,310.521459,-6.986781,21.468641
std,65.859123,3.308412e+08,3.086383e+12,62.988171,0.123566,1972.092032,62.199548,1721.913018,2273.281696,99.512520,...,17.448980,9.282343,0.015362,0.045687,0.062888,0.003048,2414.076755,1812.363570,259.018184,62.637598
min,1750.000000,2.150000e+02,4.998000e+07,0.000000,0.000000,0.000000,-1928.339000,-100.000000,-84.560000,-2298.978000,...,0.000000,-0.824000,-0.001000,0.000000,-0.001000,0.000000,-19.725000,0.000000,-2177.807000,-98.281000
25%,1875.000000,3.272140e+05,7.874038e+09,0.000000,0.000000,0.381000,-0.005000,-1.070500,6.667750,-0.727500,...,0.144000,0.003000,0.000000,0.000000,0.000000,0.000000,1.502000,0.221000,-2.262250,-6.828750
50%,1925.000000,2.291264e+06,2.743861e+10,0.000000,0.001000,5.081000,0.044000,3.813000,28.120000,0.112000,...,0.588500,0.081000,0.000000,0.000000,0.000000,0.000000,14.605500,2.222000,1.641000,8.381500
75%,1975.000000,9.986553e+06,1.212627e+11,0.524000,0.077000,53.656500,1.018000,10.884000,124.303250,2.765250,...,2.416500,0.373000,0.000000,0.001000,0.002000,0.000000,76.508500,27.863000,11.425500,32.782250
max,2024.000000,8.161973e+09,1.301126e+14,1666.885000,2.484000,38598.578000,1804.657000,180870.000000,43184.086000,2614.874000,...,100.000000,100.000000,0.377000,1.216000,1.678000,0.085000,54433.398000,43714.777000,1768.846000,1023.042000

In [41]:
a.isnull().sum()

country                                          0
year                                             0
iso_code                                      7931
population                                    9244
gdp                                          35160
cement_co2                                   21238
cement_co2_per_capita                        24763
co2                                          21027
co2_growth_abs                               23195
co2_growth_prct                              24172
co2_including_luc                            26615
co2_including_luc_growth_abs                 26915
co2_including_luc_growth_prct                26915
co2_including_luc_per_capita                 26654
co2_including_luc_per_gdp                    33621
co2_including_luc_per_unit_energy            40278
co2_per_capita                               23902
co2_per_gdp                                  32883
co2_per_unit_energy                          39585
coal_co2                                     28486
coal_co2_per_capita                          29097
consumption_co2                              45358
consumption_co2_per_capita                   45768
consumption_co2_per_gdp                      45963
cumulative_cement_co2                        21260
cumulative_co2                               22848
cumulative_co2_including_luc                 26615
cumulative_coal_co2                          28486
cumulative_flaring_co2                       34300
cumulative_gas_co2                           32264
cumulative_luc_co2                           12961
cumulative_oil_co2                           24953
cumulative_other_co2                         47157
energy_per_capita                            39825
energy_per_gdp                               42624
flaring_co2                                  34237
flaring_co2_per_capita                       35501
gas_co2                                      32264
gas_co2_per_capita                           32965
ghg_excluding_lucf_per_capita                14569
ghg_per_capita                               14232
land_use_change_co2                          12961
land_use_change_co2_per_capita               13776
methane                                      12261
methane_per_capita                           14232
nitrous_oxide                                11911
nitrous_oxide_per_capita                     13972
oil_co2                                      24952
oil_co2_per_capita                           25689
other_co2_per_capita                         47752
other_industry_co2                           47157
primary_energy_consumption                   39780
share_global_cement_co2                      28141
share_global_co2                             22848
share_global_co2_including_luc               26615
share_global_coal_co2                        28486
share_global_cumulative_cement_co2           28141
share_global_cumulative_co2                  22848
share_global_cumulative_co2_including_luc    26615
share_global_cumulative_coal_co2             28486
share_global_cumulative_flaring_co2          39322
share_global_cumulative_gas_co2              35244
share_global_cumulative_luc_co2              12961
share_global_cumulative_oil_co2              26578
share_global_cumulative_other_co2            48241
share_global_flaring_co2                     39322
share_global_gas_co2                         35244
share_global_luc_co2                         12961
share_global_oil_co2                         26578
share_global_other_co2                       48241
share_of_temperature_change_from_ghg          9173
temperature_change_from_ch4                  12131
temperature_change_from_co2                   9173
temperature_change_from_ghg                   9173
temperature_change_from_n2o                  12131
total_ghg                                    12261
total_ghg_excluding_lucf                     12598
trade_co2                                    45699
trade_co2_share                              45699
dtype: int64

In [42]:
a[a["co2"].notna()]["year"].min()

np.int64(1750)

In [43]:
a.columns

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2',
       'trade_co2_share'],
      dtype='str')

In [44]:
a[a["co2"].notna()]["year"].min()

np.int64(1750)

In [45]:
a["co2"].dtype

dtype('float64')

In [46]:
a["co2"].isna().sum()

np.int64(21027)

In [47]:
a.groupby("year")["co2"].agg(["count", "size"])

      count  size
year
1750     14    58
1751     14    58
1752     14    58
1753     14    58
1754     14    58
1755     14    58
1756     14    58
1757     14    58
1758     14    58
1759     14    58
1760     14    58
1761     14    58
1762     14    58
1763     14    58
1764     14    58
1765     14    58
1766     14    58
1767     14    58
1768     14    58
1769     14    58
1770     14    58
1771     14    58
1772     14    58
1773     14    58
1774     14    58
1775     14    58
1776     14    58
1777     14    58
1778     14    58
1779     14    58
1780     14    58
1781     14    58
1782     14    58
1783     14    58
1784     14    58
1785     17    59
1786     17    59
1787     17    59
1788     17    59
1789     17    59
1790     17    59
1791     17    59
1792     19    60
1793     19    60
1794     19    60
1795     19    60
1796     19    60
1797     19    60
1798     19    60
1799     19    60
1800     21    62
1801     21    62
1802     23    64
1803     21    62
1804     22    63
1805     21    62
1806     21    62
1807     22    63
1808     21    62
1809     21    62
1810     22    63
1811     22    63
1812     22    63
1813     22    63
1814     22    63
1815     22    63
1816     22    63
1817     22    63
1818     22    63
1819     23    64
1820     23    64
1821     23    64
1822     23    64
1823     23    64
1824     23    64
1825     23    64
1826     23    64
1827     23    64
1828     23    64
1829     23    64
1830     43    82
1831     43    82
1832     43    82
1833     43    82
1834     27    68
1835     26    67
1836     26    67
1837     26    67
1838     26    67
1839     27    68
1840     27    68
1841     27    68
1842     27    68
1843     28    69
1844     30    70
1845     30    70
1846     31    70
1847     31    70
1848     30    69
1849     30    69
1850     58   238
1851     41   252
1852     41   252
1853     41   252
1854     41   252
1855     58   252
1856     49   252
1857     49   252
1858     68   252
1859     68   252
1860     72   252
1861     72   252
1862     73   252
1863     72   252
1864     73   252
1865     74   252
1866     74   252
1867     74   252
1868     75   252
1869     75   252
1870     84   252
1871     84   252
1872     84   252
1873     84   252
1874     84   252
1875     84   252
1876     83   252
1877     83   252
1878     84   252
1879     85   252
1880     85   252
1881     86   252
1882     85   252
1883     86   252
1884     87   252
1885     93   252
1886     87   252
1887     87   252
1888     88   252
1889     87   252
1890     95   252
1891     95   252
1892     98   252
1893     98   252
1894     98   252
1895     98   252
1896     98   252
1897     98   252
1898     98   252
1899     98   252
1900     98   252
1901     98   252
1902     98   252
1903     99   252
1904    100   252
1905    103   252
1906    101   252
1907    102   252
1908    102   252
1909    106   252
1910    107   252
1911    107   252
1912    107   252
1913    109   252
1914    103   252
1915    105   252
1916    107   252
1917    104   252
1918    107   252
1919    112   252
1920    114   252
1921    114   252
1922    112   252
1923    112   252
1924    113   252
1925    113   252
1926    117   252
1927    119   252
1928    122   252
1929    122   252
1930    123   252
1931    126   252
1932    126   252
1933    131   252
1934    130   252
1935    130   252
1936    131   252
1937    131   252
1938    131   252
1939    133   252
1940    132   252
1941    128   252
1942    125   252
1943    132   252
1944    131   252
1945    132   252
1946    134   252
1947    138   252
1948    139   252
1949    142   252
1950    204   252
1951    206   252
1952    207   253
1953    207   253
1954    208   253
1955    212   253
1956    212   253
1957    212   253
1958    212   253
1959    217   253
1960    217   253
1961    218   253
1962    220   253
1963    221   253
1964    224   253
1965    225   253
1966    225   253
1967    225   253
1968    226   253
1969    226   253
1970    229   253
1971    230   253
1972    231   253
1973    230   252
1974    230   252
1975    230   252
1976    230   252
1977    230   252
1978    230   252
1979    230   252
1980    230   252
1981    231   252
1982    231   252
1983    231   252
1984    230   252
1985    230   252
1986    230   252
1987    231   252
1988    231   252
1989    231   252
1990    238   252
1991    240   253
1992    241   252
1993    241   252
1994    247   254
1995    247   254
1996    247   254
1997    247   254
1998    247   254
1999    247   254
2000    247   254
2001    247   254
2002    247   254
2003    247   254
2004    247   254
2005    247   254
2006    247   254
2007    247   254
2008    247   254
2009    247   254
2010    247   254
2011    247   254
2012    247   254
2013    247   254
2014    247   254
2015    247   254
2016    247   254
2017    247   254
2018    247   254
2019    247   254
2020    247   254
2021    247   254
2022    247   254
2023    247   254
2024    247   254

In [48]:
a = a[a["year"] >= 1950]

In [49]:

pd.set_option("display.max_rows", None)
(a.isna().mean() * 100).sort_values(ascending=False)

share_global_cumulative_other_co2            88.569322
share_global_other_co2                       88.569322
other_co2_per_capita                         87.536873
cumulative_other_co2                         86.746734
other_industry_co2                           86.746734
consumption_co2_per_gdp                      76.569743
consumption_co2_per_capita                   75.542562
trade_co2                                    75.179098
trade_co2_share                              75.179098
consumption_co2                              73.382849
energy_per_gdp                               58.981247
gas_co2_per_capita                           51.116730
gas_co2                                      50.326591
share_global_cumulative_gas_co2              50.326591
share_global_gas_co2                         50.326591
cumulative_gas_co2                           50.326591
co2_including_luc_per_unit_energy            46.623472
energy_per_capita                            44.237252
primary_energy_consumption                   44.000211
co2_per_unit_energy                          42.973030
flaring_co2_per_capita                       42.704383
share_global_cumulative_flaring_co2          41.587653
cumulative_flaring_co2                       41.587653
share_global_flaring_co2                     41.587653
flaring_co2                                  41.255794
gdp                                          39.570164
coal_co2_per_capita                          37.805520
share_global_coal_co2                        37.015381
coal_co2                                     37.015381
cumulative_coal_co2                          37.015381
share_global_cumulative_coal_co2             37.015381
co2_including_luc_per_gdp                    35.345554
co2_per_gdp                                  34.576485
co2_including_luc_growth_abs                 20.280236
co2_including_luc_growth_prct                20.280236
share_global_cumulative_co2_including_luc    19.827223
share_global_co2_including_luc               19.827223
co2_including_luc                            19.827223
cumulative_co2_including_luc                 19.827223
co2_including_luc_per_capita                 19.827223
ghg_excluding_lucf_per_capita                17.361989
ghg_per_capita                               16.640329
land_use_change_co2_per_capita               16.640329
methane_per_capita                           16.640329
nitrous_oxide_per_capita                     15.850190
share_global_luc_co2                         15.455120
land_use_change_co2                          15.455120
cumulative_luc_co2                           15.455120
share_global_cumulative_luc_co2              15.455120
cement_co2_per_capita                        15.423515
total_ghg_excluding_lucf                     14.596502
share_global_cement_co2                      13.948588
cumulative_cement_co2                        13.948588
share_global_cumulative_cement_co2           13.948588
iso_code                                     13.874842
total_ghg                                    13.874842
methane                                      13.874842
cement_co2                                   13.832701
oil_co2_per_capita                           13.437632
co2_per_capita                               13.121576
temperature_change_from_n2o                  13.084703
temperature_change_from_ch4                  13.084703
nitrous_oxide                                13.084703
co2_growth_prct                              12.794985
share_global_cumulative_oil_co2              12.463127
share_global_oil_co2                         12.463127
cumulative_oil_co2                           12.463127
oil_co2                                      12.457859
co2_growth_abs                               12.452592
cumulative_co2                               11.894227
share_global_co2                             11.894227
share_global_cumulative_co2                  11.894227
population                                    9.529077
co2                                           7.569532
share_of_temperature_change_from_ghg          6.368521
temperature_change_from_ghg                   6.368521
temperature_change_from_co2                   6.368521
year                                          0.000000
country                                       0.000000
dtype: float64

In [50]:
a.duplicated().sum()

np.int64(0)

In [51]:
a.dtypes

country                                          str
year                                           int64
iso_code                                         str
population                                   float64
gdp                                          float64
cement_co2                                   float64
cement_co2_per_capita                        float64
co2                                          float64
co2_growth_abs                               float64
co2_growth_prct                              float64
co2_including_luc                            float64
co2_including_luc_growth_abs                 float64
co2_including_luc_growth_prct                float64
co2_including_luc_per_capita                 float64
co2_including_luc_per_gdp                    float64
co2_including_luc_per_unit_energy            float64
co2_per_capita                               float64
co2_per_gdp                                  float64
co2_per_unit_energy                          float64
coal_co2                                     float64
coal_co2_per_capita                          float64
consumption_co2                              float64
consumption_co2_per_capita                   float64
consumption_co2_per_gdp                      float64
cumulative_cement_co2                        float64
cumulative_co2                               float64
cumulative_co2_including_luc                 float64
cumulative_coal_co2                          float64
cumulative_flaring_co2                       float64
cumulative_gas_co2                           float64
cumulative_luc_co2                           float64
cumulative_oil_co2                           float64
cumulative_other_co2                         float64
energy_per_capita                            float64
energy_per_gdp                               float64
flaring_co2                                  float64
flaring_co2_per_capita                       float64
gas_co2                                      float64
gas_co2_per_capita                           float64
ghg_excluding_lucf_per_capita                float64
ghg_per_capita                               float64
land_use_change_co2                          float64
land_use_change_co2_per_capita               float64
methane                                      float64
methane_per_capita                           float64
nitrous_oxide                                float64
nitrous_oxide_per_capita                     float64
oil_co2                                      float64
oil_co2_per_capita                           float64
other_co2_per_capita                         float64
other_industry_co2                           float64
primary_energy_consumption                   float64
share_global_cement_co2                      float64
share_global_co2                             float64
share_global_co2_including_luc               float64
share_global_coal_co2                        float64
share_global_cumulative_cement_co2           float64
share_global_cumulative_co2                  float64
share_global_cumulative_co2_including_luc    float64
share_global_cumulative_coal_co2             float64
share_global_cumulative_flaring_co2          float64
share_global_cumulative_gas_co2              float64
share_global_cumulative_luc_co2              float64
share_global_cumulative_oil_co2              float64
share_global_cumulative_other_co2            float64
share_global_flaring_co2                     float64
share_global_gas_co2                         float64
share_global_luc_co2                         float64
share_global_oil_co2                         float64
share_global_other_co2                       float64
share_of_temperature_change_from_ghg         float64
temperature_change_from_ch4                  float64
temperature_change_from_co2                  float64
temperature_change_from_ghg                  float64
temperature_change_from_n2o                  float64
total_ghg                                    float64
total_ghg_excluding_lucf                     float64
trade_co2                                    float64
trade_co2_share                              float64
dtype: object

In [52]:
for column in a.columns:
    if a[column].isna().mean() * 100 > 70:
        a.drop(columns=[column], inplace=True)

In [53]:
a = a[a["iso_code"].notna()]

In [54]:
# Q1 — Which 10 countries emitted the most CO₂ in 2023, and how has their share of global emissions changed since 1990?

countries_high = (
    a[a["year"] == 2023]
    .groupby("country")["co2"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

countries_past = (
    a[
        (a["year"] == 1990) &
        (a["country"].isin(countries_high.index))
    ]
)[["country", "share_global_co2"]]

# Plotly Visualization

fig = px.bar(
    countries_high.reset_index(),
    x="co2",
    y="country",
    orientation="h",
    title="Top 10 CO₂ Emitting Countries in 2023",
    labels={
        "co2": "CO₂ Emissions (Million Tonnes)",
        "country": "Country"
    },
    template="plotly_white",
    text="co2",
    height=600
)

fig.update_yaxes(autorange="reversed")

fig.update_traces(
    texttemplate="%{text:.0f}",
    textposition="outside"
)

fig.update_layout(
    title_x=0.5,
    xaxis_title="CO₂ Emissions (Million Tonnes)",
    yaxis_title="Country"
)

fig.show()

In [55]:
# Q2 — Which countries have the highest CO₂ emissions per capita in 2023?
q2 = (
    a[a["year"] == 2023]
    .sort_values("co2_per_capita", ascending=False)
    [["country","co2_per_capita"]]
    .head(10)
)

fig = px.bar(
    q2,
    x="co2_per_capita",
    y="country",
    orientation="h",
    title="Top 10 Countries by CO₂ Per Capita (2023)",
    template="plotly_white"
)

fig.update_yaxes(autorange="reversed")
fig.show()

In [56]:
# Q3 — How have global CO₂ emissions changed since 1990?

q3 = (
    a[a["year"] >= 1990]
    .groupby("year")["co2"]
    .sum()
    .reset_index()
)

fig = px.line(
    q3,
    x="year",
    y="co2",
    title="Global CO₂ Emissions Since 1990",
    template="plotly_white"
)

fig.show()

In [57]:
# Q4 — Which countries reduced CO₂ emissions the most between 1990 and 2023?

co2_1990 = a[a["year"]==1990][["country","co2"]].rename(columns={"co2":"co2_1990"})
co2_2023 = a[a["year"]==2023][["country","co2"]].rename(columns={"co2":"co2_2023"})

q4 = pd.merge(co2_1990, co2_2023, on="country")

q4["reduction"] = q4["co2_1990"] - q4["co2_2023"]

q4 = q4.sort_values("reduction", ascending=False).head(10)

fig = px.bar(
    q4,
    x="reduction",
    y="country",
    orientation="h",
    title="Countries with Largest CO₂ Reduction (1990–2023)",
    template="plotly_white"
)

fig.update_yaxes(autorange="reversed")
fig.show()

In [58]:
# Q5 — Is there a relationship between population and CO₂ emissions in 2023?

q5 = a[a["year"]==2023][["country","population","co2"]].dropna()

fig = px.scatter(
    q5,
    x="population",
    y="co2",
    hover_name="country",
    title="Population vs CO₂ Emissions (2023)",
    template="plotly_white"
)

fig.show()

In [59]:
# Q6 — Relationship between GDP and CO₂ (2022)

q6 = a[a["year"]==2022][["country","gdp","co2"]].dropna()

fig = px.scatter(
    q6,
    x="gdp",
    y="co2",
    hover_name="country",
    title="GDP vs CO₂ Emissions (2022)",
    template="plotly_white"
)

fig.show()

In [60]:
# Q7 — G7 CO₂ Trend Since 1990

g7 = [
    "Canada",
    "France",
    "Germany",
    "Italy",
    "Japan",
    "United Kingdom",
    "United States"
]

q7 = a[
    (a["country"].isin(g7)) &
    (a["year"]>=1990)
]

fig = px.line(
    q7,
    x="year",
    y="co2",
    color="country",
    title="G7 CO₂ Emission Trends Since 1990",
    template="plotly_white"
)

fig.show()

In [61]:
#Q8 — Coal, Oil and Gas CO₂ Since 1990

q8 = (
    a[a["year"]>=1990]
    .groupby("year")[["coal_co2","oil_co2","gas_co2"]]
    .sum()
    .reset_index()
)

q8 = q8.melt(
    id_vars="year",
    var_name="Fuel",
    value_name="CO₂"
)

fig = px.line(
    q8,
    x="year",
    y="CO₂",
    color="Fuel",
    title="Global CO₂ by Fuel Type Since 1990",
    template="plotly_white"
)

fig.show()

In [62]:
# Q9 — Which countries experienced the largest increase in CO₂ emissions between 1990 and 2023?

co2_1990 = a[a["year"] == 1990][["country","co2"]].rename(columns={"co2":"co2_1990"})
co2_2023 = a[a["year"] == 2023][["country","co2"]].rename(columns={"co2":"co2_2023"})

q9 = pd.merge(co2_1990, co2_2023, on="country")

q9["Increase"] = q9["co2_2023"] - q9["co2_1990"]

q9 = q9.sort_values("Increase", ascending=False).head(10)

fig = px.bar(
    q9,
    x="Increase",
    y="country",
    orientation="h",
    title="Top 10 Countries with the Largest CO₂ Increase (1990–2023)",
    template="plotly_white"
)

fig.update_yaxes(autorange="reversed")
fig.show()

In [63]:
#Q10 — Which countries have the highest CO₂ emissions per unit of GDP? (2022)


q10 = (
    a[a["year"] == 2022]
    .dropna(subset=["co2_per_gdp"])
    .sort_values("co2_per_gdp", ascending=False)
    [["country","co2_per_gdp"]]
    .head(10)
)

fig = px.bar(
    q10,
    x="co2_per_gdp",
    y="country",
    orientation="h",
    title="Top 10 Countries by CO₂ per GDP (2022)",
    template="plotly_white"
)

fig.update_yaxes(autorange="reversed")
fig.show()